### ISSUE TITLE
Does not decompile inner classes

### ISSUE THREAD

**Issue by m0skit0** [kwart/jd-cli#31]
When selecting a folder for decompilation, there's no output for inner classes, e.g MyClass$MyInnerClass.class. Renaming the classes to remove the $ character solves the problem.

**Comment by kwart** [comment]
Have you used the 1.0.1 version? The 1.0.0 had the problem and it should be fixed in 1.0.1.

**Comment by m0skit0** [comment]
Sorry for the late reply. Yes, I'm using 1.0.1, also the only version I used. I cannot reproduce now because I automated the renaming of any files with $ on them.  I'm running on Windows 10, not sure if this might affect the decompilation.

**Comment by kwart** [comment]
A sample class/jar which caused you troubles would help. And also command line parameters used.

**Comment by kwart** [comment]
This should be resolved in version 1.2.0, therefore closing.
Feel free to reopen if you still hit the problem.
