### ISSUE TITLE
Missing inner class

### ISSUE THREAD

**Issue by kaifeng-h** [kwart/jd-cli#46]
Hi.
I'm using the latest release version to decompile rt.jar(normally it is located at $JDK_HOME/jre/lib/rt.jar), which is the official JDK jar. I can not find SimpleImmutableEntry in java.util.AbstractMap.java, which is an inner static class in AbstractMap. The weird thing is that, SimpleImmutableEntry does exist in AbstractMap when I was using [JD-GUI](https://java-decompiler.github.io/) and the same rt.jar to check.

**Comment by kwart** [comment]
Thanks for the report. The issue should be fixed in the next release.

**Comment by kaifeng-h** [comment]
Thanks. Will the release be ready soon? Or it will be released until other issues/task to be done?

**Comment by kwart** [comment]
I would like to do the release this week.

**Comment by kaifeng-h** [comment]
Appreciate it very much 👍

**Comment by kwart** [comment]
1.2.0 is released.

**Comment by kaifeng-h** [comment]
Already using it. Thx
